[package]
name = "clust"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.28"
crossterm = "0.28"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
dirs = "5"
lazy_static = "1.5.0"
whoami = "1.2.0"

[dev-dependencies]
tempfile = "3"

